insert into endereco (idendereco, rua, bairro, cidade, estado) values (1, '497 Hoffman Plaza', 'Guatemalan', 'Huntsville', 'Alabama');
insert into endereco (idendereco, rua, bairro, cidade, estado) values (2, '4051 Grayhawk Drive', 'Creek', 'Amarillo', 'Texas');
insert into endereco (idendereco, rua, bairro, cidade, estado) values (3, '77018 Mcguire Trail', 'Eskimo', 'Hayward', 'California');
insert into endereco (idendereco, rua, bairro, cidade, estado) values (4, '36 Grayhawk Terrace', 'Paiute', 'Bronx', 'New York');
insert into endereco (idendereco, rua, bairro, cidade, estado) values (5, '87 Havey Circle', 'Micronesian', 'Glendale', 'Arizona');
insert into endereco (idendereco, rua, bairro, cidade, estado) values (6, '51 Mcguire Crossing', 'Guamanian', 'Phoenix', 'Arizona');
insert into endereco (idendereco, rua, bairro, cidade, estado) values (7, '23 Corben Trail', 'Honduran', 'Fort Pierce', 'Florida');
insert into endereco (idendereco, rua, bairro, cidade, estado) values (8, '91 Gina Drive', 'Paraguayan', 'Texarkana', 'Texas');
insert into endereco (idendereco, rua, bairro, cidade, estado) values (9, '9 Derek Circle', 'Alaskan Athabascan', 'Saint Petersburg', 'Florida');
insert into endereco (idendereco, rua, bairro, cidade, estado) values (10, '1304 Morningstar Alley', 'Asian Indian', 'Round Rock', 'Texas');
