insert into livro (idlivro, titulo, preco, editora, idioma, genero, ano, numeroPaginas) values (1, 'Brain Dead', '$104.36', 'Oyondu', 'Hungarian', 'Horror|Sci-Fi', 1995, 990);
insert into livro (idlivro, titulo, preco, editora, idioma, genero, ano, numeroPaginas) values (2, 'In a Town This Size', '$213.40', 'Rooxo', 'Polish', 'Documentary', 2007, 601);
insert into livro (idlivro, titulo, preco, editora, idioma, genero, ano, numeroPaginas) values (3, 'Three Faces East', '$37.38', 'Tagcat', 'Kurdish', 'Drama|Mystery|War', 1999, 788);
insert into livro (idlivro, titulo, preco, editora, idioma, genero, ano, numeroPaginas) values (4, 'Mystery of the Wax Museum', '$190.22', 'Twitterbeat', 'Gujarati', 'Horror', 2012, 184);
insert into livro (idlivro, titulo, preco, editora, idioma, genero, ano, numeroPaginas) values (5, 'Slipping-Down Life, A', '$36.24', 'Babblestorm', 'German', 'Drama|Romance', 1998, 607);
insert into livro (idlivro, titulo, preco, editora, idioma, genero, ano, numeroPaginas) values (6, 'Soldier''s Daughter Never Cries, A', '$144.36', 'Quinu', 'Romanian', 'Drama', 2006, 864);
insert into livro (idlivro, titulo, preco, editora, idioma, genero, ano, numeroPaginas) values (7, 'Chris Rock: Bring the Pain', '$222.64', 'Youbridge', 'Icelandic', 'Comedy', 1994, 924);
insert into livro (idlivro, titulo, preco, editora, idioma, genero, ano, numeroPaginas) values (8, 'Murders in the Zoo', '$49.92', 'Izio', 'Yiddish', 'Crime|Horror|Mystery', 2010, 415);
insert into livro (idlivro, titulo, preco, editora, idioma, genero, ano, numeroPaginas) values (9, 'Cuenca Crime, The (Crimen de Cuenca, El)', '$136.68', 'Wordpedia', 'Lithuanian', 'Drama', 2010, 285);
insert into livro (idlivro, titulo, preco, editora, idioma, genero, ano, numeroPaginas) values (10, 'Learning Curve, The', '$133.88', 'Oloo', 'Marathi', 'Crime|Drama|Thriller', 1993, 414);
insert into livro (idlivro, titulo, preco, editora, idioma, genero, ano, numeroPaginas) values (11, 'River, The', '$117.13', 'Eazzy', 'Malayalam', 'Drama', 1995, 935);
insert into livro (idlivro, titulo, preco, editora, idioma, genero, ano, numeroPaginas) values (12, 'Illusion Of Blood', '$174.47', 'Meedoo', 'Haitian Creole', 'Fantasy|Horror', 1995, 903);
insert into livro (idlivro, titulo, preco, editora, idioma, genero, ano, numeroPaginas) values (13, 'Leprechaun: Origins', '$65.54', 'Vipe', 'Northern Sotho', 'Horror', 2012, 412);
insert into livro (idlivro, titulo, preco, editora, idioma, genero, ano, numeroPaginas) values (14, 'Bullfighters, The', '$223.25', 'Zoomdog', 'Catalan', 'Comedy|Musical', 1987, 329);
insert into livro (idlivro, titulo, preco, editora, idioma, genero, ano, numeroPaginas) values (15, 'Dark Star', '$206.21', 'Wikivu', 'Montenegrin', 'Comedy|Sci-Fi|Thriller', 1955, 854);
insert into livro (idlivro, titulo, preco, editora, idioma, genero, ano, numeroPaginas) values (16, 'Devil and Daniel Webster, The (All That Money Can Buy)', '$127.06', 'Skimia', 'Portuguese', 'Drama|Fantasy', 1996, 141);
insert into livro (idlivro, titulo, preco, editora, idioma, genero, ano, numeroPaginas) values (17, 'Fog of War: Eleven Lessons from the Life of Robert S. McNamara, The', '$211.76', 'Gigaclub', 'Hungarian', 'Documentary|War', 2009, 855);
insert into livro (idlivro, titulo, preco, editora, idioma, genero, ano, numeroPaginas) values (18, 'Wrong Is Right (a.k.a. The Man With the Deadly Lens)', '$131.03', 'Skynoodle', 'Lao', 'Drama|Thriller', 1996, 906);
insert into livro (idlivro, titulo, preco, editora, idioma, genero, ano, numeroPaginas) values (19, 'Target', '$105.08', 'Tagopia', 'Azeri', 'Action|Drama|Thriller', 1994, 632);
insert into livro (idlivro, titulo, preco, editora, idioma, genero, ano, numeroPaginas) values (20, 'Stewart Lee: If You Prefer a Milder Comedian, Please Ask for One', '$181.38', 'Jabbersphere', 'West Frisian', 'Comedy', 1997, 699);
